apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: web-scraper
data:
  pageUrl: $PAGE_URL
  pageSelector: $PAGE_SELECTOR
  chromeHost: chrome-svc
  smtpHost: $SMTP_HOST
  mailSubject: $MAIL_SUBJECT
  mailSender: $MAIL_SENDER
  mailSenderName: $MAIL_SENDER_NAME
  healthCheckUrl: $HEALTH_CHECK_URL
