apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
  namespace: web-scraper
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: namshi/smtp:latest
        ports:
        - containerPort: 25
        env:
        - name: RELAY_NETWORKS
          value: ":10.0.0.0/8:127.0.0.0/8:172.17.0.0/16:192.0.0.0/8"
        - name: GMAIL_USER
          valueFrom: 
            secretKeyRef:
              name: app-secrets
              key: gmailUser
        - name: GMAIL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: app-secrets
              key: gmailPassword
---
apiVersion: v1
kind: Service
metadata:
  name: email-svc
  namespace: web-scraper
spec:
  selector:
    app: email
  ports:
  - protocol: TCP
    port: 25
    targetPort: 25
