name: Validate K8S files
on: push
jobs:
  container:
    runs-on: ubuntu-latest
    container: deck15/kubeval-tools:latest
    steps:
      - uses: actions/checkout@master
      - run: |
          kubeconform -summary k8s/*.yml
