name: Validate K8S files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -OL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz &&
          tar xf kubeval-linux-amd64.tar.gz &&
          ./kubeval k8s/*
